services:
  container1:
    image: python:3.9-slim
    container_name: container1
    volumes:
      - ./server.py:/app/server.py  # Monta server.py
      - ./data/container1:/app/data
    ports:
      - "5001:5000"
    working_dir: /app
    environment:
      - FLASK_ENV=development
    command: >
      sh -c "pip install flask && python server.py"

  container2:
    image: python:3.9-slim
    container_name: container2
    volumes:
      - ./server.py:/app/server.py  # Monta server.py
      - ./data/container2:/app/data
    ports:
      - "5002:5000"
    working_dir: /app
    environment:
      - FLASK_ENV=development
    command: >
      sh -c "pip install flask && python server.py"

  container3:
    image: python:3.9-slim
    container_name: container3
    volumes:
      - ./server.py:/app/server.py  # Monta server.py
      - ./data/container3:/app/data
    ports:
      - "5003:5000"
    working_dir: /app
    environment:
      - FLASK_ENV=development
    command: >
      sh -c "pip install flask && python server.py"
